# Generated by Django 6.0.3 on 2026-04-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('grau', models.CharField(choices=[('bacharelado', 'Bacharelado'), ('licenciatura', 'Licenciatura'), ('tecnologo', 'Tecnólogo')], max_length=50)),
                ('qtd_semestres', models.IntegerField()),
            ],
        ),
    ]
