# Generated by Django 6.0.3 on 2026-04-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nome', 'grau')},
        ),
    ]
