# Generated by Django 6.0.3 on 2026-04-02 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='cursos.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.disciplina')),
            ],
            options={
                'unique_together': {('curso', 'disciplina', 'semestre')},
            },
        ),
    ]
