# Generated by Django 6.0.3 on 2026-04-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='semestre',
            field=models.IntegerField(default=1),
        ),
    ]
